[package]
name = "shootout"
version = "0.1.0"
authors = ["Andrey Larionov <anlarionov@gmail.com>"]

[dependencies]
hyper = { git = "https://github.com/hyperium/hyper.git", rev = "8b3c1206846cb96be780923952eafe0dde7850bf" }
env_logger="0.3.4"

